### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by AlpacaKnight** [wangzhaode/stable-diffusion-mnn#1]
执行make时失败

/usr/bin/ld: CMakeFiles/main.dir/src/pipeline.cpp.o: in function `diffusion::Pipeline::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
pipeline.cpp:(.text+0x3d94): undefined reference to `MNN::CV::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MNN::Express::VARP, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:129：main] 错误 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/main.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2

**Comment by wangzhaode** [comment]
有没有拷贝`libMNNOpenCV.so`到libs目录下呢

**Comment by AlpacaKnight** [comment]
> 有没有拷贝`libMNNOpenCV.so`到libs目录下呢

确定三个so文件都拷贝了，也是新编译的，还比较了include文件确保版本一致，make时仍然报此错误

**Comment by wangzhaode** [comment]
编译MNN库的时候,`cmake`需要使用`-DMNN_IMGCODECS=ON`参数才会编译`imwrite`函数，请检查一下是否打开该选项

**Comment by AlpacaKnight** [comment]
> 编译MNN库的时候,`cmake`需要使用`-DMNN_IMGCODECS=ON`参数才会编译`imwrite`函数，请检查一下是否打开该选项

谢谢，已经可以编译了，你的readme文件中命令部分有点小小的错误，这是修改后的

```
git clone https://github.com/alibaba/MNN.git
cd MNN
mkdir build
cd build
cmake -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON ..
make -j8
cp libMNN.so express/libMNN_Express.so tools/cv/libMNNOpenCV.so /path/to/stable-diffusion-mnn/libs
```

**Comment by wangzhaode** [comment]
嗯 是的 感谢提醒 已修改

**Comment by fuerpy** [comment]
android shell 运行
CANNOT LINK EXECUTABLE "./main": library "libMNN.so" not found: needed by main executable
报这个错误
