### ISSUE TITLE
无法复现demo中的结果

### ISSUE THREAD

**Issue by wildkid1024** [wangzhaode/stable-diffusion-mnn#3]
原有模型大小大概18g，去掉safety_checker也有16g，但是mnn模型只有不到2g，似乎做了int4量化，所以对模型的量化精度感到疑惑，int4模型的精度损失较大，基本丢失了中文语义。

**Comment by wangzhaode** [comment]
- 按照README执行可以复现；
- 原始模型的权重大小是[4.18G](https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/blob/main/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt);
- 模型权重是使用fp16存储的，不是int4;

**Comment by wildkid1024** [comment]
可以用跑一遍太乙->onnx->mnn的流程，fp16是有损失的。

**Comment by youknowzjz6** [comment]
> > 可以用跑一遍太乙->onnx->mnn的流程，fp16是有损失的。
> 
> fp16精度损失很小

请问一下，大于2GB的unet是如何让转换成unet.mnn的？每次输入同一句话生成的图不一样。

**Comment by wangzhaode** [comment]
> 的

请重新下载一下 text_encoder 模型
