### ISSUE TITLE
生成结果一团artefacts，无法复现

### ISSUE THREAD

**Issue by yjhdhr** [wangzhaode/stable-diffusion-mnn#4]
您好，我最近也在坐mnn 跑 stabel diffusion，我发现了你的项目并且尝试复现，一切都是那么流畅，只不过我是用的cpu跑得。
最终结果看起来并不是表述的内容，是的一堆乱七八糟的东西。。你可以用cpu后端跑一次试试吗？

**Comment by jianwenyyy** [comment]
同cpu后端无法复现， mnn版本2.5.0

**Comment by 791136190** [comment]
![demo](https://github.com/wangzhaode/stable-diffusion-mnn/assets/27891060/5c8e4c8d-f4b1-41ba-985a-066cf2d02375)
result like this

**Comment by wangzhaode** [comment]
> 您好，我最近也在坐mnn 跑 stabel diffusion，我发现了你的项目并且尝试复现，一切都是那么流畅，只不过我是用的cpu跑得。 最终结果看起来并不是表述的内容，是的一堆乱七八糟的东西。。你可以用cpu后端跑一次试试吗？

ok 稍等我用最新版代码测试一下看看

**Comment by wangzhaode** [comment]
我测试了一下，使用最新版本的MNN测试确实有问题；

我定位一下问题

**Comment by 791136190** [comment]
> 我测试了一下，使用最新版本的MNN测试确实有问题；
> 
> 我定位一下问题


我已经找到问题了，是因为你提供的text encoder输入维度是1 X 512的，导致这里
std::unique_ptr<Tensor> idsTensor(Tensor::create(input->shape(), input->getType(), const_cast<int*>(ids.data()), input->getDimensionType()));拷贝的时候只把uncond部分拷贝进去了
在你的text encoder里面加上resize，然后把load net的release取消就行了。我是直接写死了维度    
mNet->resizeTensor(input, {2, 512});
mNet->resizeTensor(output, {2, 512, 768});
mNet->resizeSession(mSession);
更合理的做法应该考虑把本身的shape读出来，然后把batch维度改掉
下面是我修改后运行的一次示例：
![ test](https://github.com/wangzhaode/stable-diffusion-mnn/assets/27891060/c042c23c-ea9c-450b-aa2f-190cefc97063)

**Comment by wangzhaode** [comment]
> 在你的text encoder里面加上resize，然后把load net的release取消就行了。我是直接写死了维度

这个不存在问题，release中的text_encoder模型输入我已经固定为[2, 512]了，如果你是从onnx模型转换过来的那确实需要重新设置一下

**Comment by wangzhaode** [comment]
> 同cpu后端无法复现， mnn版本2.5.0

2.5.0 MNN CPU/CUDA测试正常，测试时模型必须使用 release 中下载的模型：
https://github.com/wangzhaode/stable-diffusion-mnn/releases/tag/v0.1

**Comment by wangzhaode** [comment]
如果自己转换模型需要修改代码或者模型的输入shape才可以

**Comment by 791136190** [comment]
> > 在你的text encoder里面加上resize，然后把load net的release取消就行了。我是直接写死了维度
> 
> 这个不存在问题，release中的text_encoder模型输入我已经固定为[2, 512]了，如果你是从onnx模型转换过来的那确实需要重新设置一下

那这就很神奇了，我用你release中的模型，text encoder读出来input的batch确实为1，unet的batch都为2，所以我加了前面我说的那一句，然后就可以了。我使用的时MNN 2.5 @ cpu x86_x64后端

**Comment by wangzhaode** [comment]
> > > 在你的text encoder里面加上resize，然后把load net的release取消就行了。我是直接写死了维度
> > 
> > 
> > 这个不存在问题，release中的text_encoder模型输入我已经固定为[2, 512]了，如果你是从onnx模型转换过来的那确实需要重新设置一下
> 
> 那这就很神奇了，我用你release中的模型，text encoder读出来input的batch确实为1，unet的batch都为2，所以我加了前面我说的那一句，然后就可以了。我使用的时MNN 2.5 @ cpu x86_x64后端

抱歉 找到原因了 release里的模型是旧的

**Comment by wangzhaode** [comment]
我上传的这3个模型 text_encoder 传错了 我重新上传一下

**Comment by wangzhaode** [comment]
重新上传了 text_encoder； 2.5.0及以前版本均可运行

**Comment by 791136190** [comment]
> 重新上传了 text_encoder； 2.5.0及以前版本均可运行

我用你提供的to onnx脚本转换得到了动态batch的3个模型，然后用类似这样的命令转换得到mnn模型：
 ./MNNConvert -f ONNX --modelFile chinese/vae_decoder/model.onnx --MNNModel vae_decoder.mnn --bizCode biz --keepInputFormat --fp16
虽然得到了模型，并且也能通过手动设置shape运行起来，但是结果不对，想了解下你的转换模型命令是怎么样的？
