### ISSUE TITLE
关于模型导出

### ISSUE THREAD

**Issue by 791136190** [wangzhaode/stable-diffusion-mnn#5]
你好
     现在使用你提供的mnn模型可以正常推理，但是我使用你提供的to_onnx.py脚本导出onnx模型，然后转换为mnn模型就无法正常计算。通过排查发现text encode和vue decoder都是ok的，问题出在unet部分，想了解下你在导出unet的时候是还需要进行什么修改吗？
导出onnx我就直接用的你的脚本，并且没有使用fp16参数，其它默认脚本中的参数，动态shape都没有修改。
转换mnn的命令是：./MNNConvert -f ONNX --modelFile chinese/unet/model.onnx --MNNModel unet.mnn --bizCode mnn --fp16

**Comment by 791136190** [comment]
可以了，在导出unet的时候，timestep_in的type保持float就行了，你给的脚本设为int了，应该是只需要把text encoder的intput设为int就行了

**Comment by fuerpy** [comment]
你好 @791136190 请教一下，unet转换到onnx的时候是不打开 --fp16 这个选项吗？使用3.7g大小的onnx再 通过 mmnconvert 打开--fp16转换到 1.6g 大小吗？感谢

**Comment by 791136190** [comment]
> 你好 @791136190 请教一下，unet转换到onnx的时候是不打开 --fp16 这个选项吗？使用3.7g大小的onnx再 通过 mmnconvert 打开--fp16转换到 1.6g 大小吗？感谢

是的，所有模型都先转为fp32的onnx，然后转mnn，至于要不要fp16可以自由选择，因为导出mnn可以将权重导出到额外的文件中，然后再load计算

**Comment by fuerpy** [comment]
@791136190 好的谢谢你的回复，但是如果转为fp32的onnx，他不是会保存成一个.onnx 和一个 weights.pb两个文件吗？我看在Mnnconvert的转换介绍中没有写这种情况如何使用命令？应该怎么转换成mnn呀

**Comment by 791136190** [comment]
> @791136190 好的谢谢你的回复，但是如果转为fp32的onnx，他不是会保存成一个.onnx 和一个 weights.pb两个文件吗？我看在Mnnconvert的转换介绍中没有写这种情况如何使用命令？应该怎么转换成mnn呀

保证在同一个目录下就行，不需要额外处理mnn会自己去读

**Comment by fuerpy** [comment]
> 可以了，在导出unet的时候，timestep_in的type保持float就行了，你给的脚本设为int了，应该是只需要把text encoder的intput设为int就行了

@791136190 您好，再次请教一下，我今天按照上面您说的fp32转mnn成功了，但是一推理就显示
[--------------------------------------------------]  [  0%]Segmentation fault
然后看到您提的这个issue的建议，但是这句话没有理解，是改动转换脚本的三个输入那里的dtype吗？我改动第三个输入从torch.float32改为 torch.int32时，会报错无法进行下去，如果第二个改为float32则没有影响，谢谢您的回复

**Comment by fuerpy** [comment]
@791136190 
            torch.randn(2, num_tokens, text_hidden_size).to(device=device, dtype=dtype),
https://github.com/wangzhaode/stable-diffusion-mnn/blob/fca03860e60d1d9099902ff8b4fecc8d1398347c/export_script/to_onnx.py#L124

您好，您的意思是把这一行的dtype改为torch.int32吗？我改动了之后会有报错，如果不是的话，能不能辛苦贴一下对应代码行，十分感谢！
